// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.jdbc;

import be.leerstad.eindwerk.dao.DAOFactory;
import be.leerstad.eindwerk.dao.LogfileDAO;
import be.leerstad.eindwerk.dao.SchoolDAO;
import be.leerstad.eindwerk.dao.SessionDAO;
import be.leerstad.eindwerk.dao.SiteDAO;
import be.leerstad.eindwerk.dao.SiteapplicationDAO;
import be.leerstad.eindwerk.dao.UserDAO;
import be.leerstad.eindwerk.dao.VisitDAO;

import java.sql.Connection;


public class JDBCDAOFactory extends DAOFactory {
    public LogfileDAO getLogfileDAO() {
        return new LogfileDAOImpl();
    }

    public LogfileDAO getLogfileDAO(Connection conn) {
        return new LogfileDAOImpl(conn);
    }

    public SchoolDAO getSchoolDAO() {
        return new SchoolDAOImpl();
    }

    public SchoolDAO getSchoolDAO(Connection conn) {
        return new SchoolDAOImpl(conn);
    }

    public SessionDAO getSessionDAO() {
        return new SessionDAOImpl();
    }

    public SessionDAO getSessionDAO(Connection conn) {
        return new SessionDAOImpl(conn);
    }

    public SiteapplicationDAO getSiteapplicationDAO() {
        return new SiteapplicationDAOImpl();
    }

    public SiteapplicationDAO getSiteapplicationDAO(Connection conn) {
        return new SiteapplicationDAOImpl(conn);
    }

    public SiteDAO getSiteDAO() {
        return new SiteDAOImpl();
    }

    public SiteDAO getSiteDAO(Connection conn) {
        return new SiteDAOImpl(conn);
    }

    public UserDAO getUserDAO() {
        return new UserDAOImpl();
    }

    public UserDAO getUserDAO(Connection conn) {
        return new UserDAOImpl(conn);
    }

    public VisitDAO getVisitDAO() {
        return new VisitDAOImpl();
    }

    public VisitDAO getVisitDAO(Connection conn) {
        return new VisitDAOImpl(conn);
    }
}
