// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.dao;

public class DAOException extends Exception {
    public DAOException(String s, Exception e) {
        super(s, e);
    }

    public DAOException(String e) {
        super(e);
    }

    public DAOException(Exception e) {
        super(e);
    }
}
