// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.dao;

import java.sql.Connection;


public abstract class DAOFactory {
    private static DAOFactory singleton;

    public static DAOFactory getInstance() throws DAOException {
        try {
            if (null == singleton) {
                singleton = (DAOFactory) Class.forName("be.leerstad.eindwerk.jdbc.JDBCDAOFactory")
                                              .newInstance();
            }
        }
        catch (Exception e) {
            throw new DAOException("Could not create the DAOFactory singleton", e);
        }

        return singleton;
    }

    public abstract LogfileDAO getLogfileDAO();

    public abstract LogfileDAO getLogfileDAO(Connection conn);

    public abstract SchoolDAO getSchoolDAO();

    public abstract SchoolDAO getSchoolDAO(Connection conn);

    public abstract SessionDAO getSessionDAO();

    public abstract SessionDAO getSessionDAO(Connection conn);

    public abstract SiteapplicationDAO getSiteapplicationDAO();

    public abstract SiteapplicationDAO getSiteapplicationDAO(Connection conn);

    public abstract SiteDAO getSiteDAO();

    public abstract SiteDAO getSiteDAO(Connection conn);

    public abstract UserDAO getUserDAO();

    public abstract UserDAO getUserDAO(Connection conn);

    public abstract VisitDAO getVisitDAO();

    public abstract VisitDAO getVisitDAO(Connection conn);
}
