// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.dao;

import be.leerstad.eindwerk.Logfile;

import java.util.Date;
import java.util.List;


public interface LogfileDAO {
    // CRUD methods
    public Logfile getByPrimaryKey(String logfile) throws DAOException;

    public List selectAll() throws DAOException;

    public List select(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public long selectCount() throws DAOException;

    public long selectCount(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public int update(Logfile obj) throws DAOException;

    public int insert(Logfile obj) throws DAOException;

    public int delete(Logfile obj) throws DAOException;

    // Finders
    public List getByLogfiledate(Date logfiledate) throws DAOException;
}
