// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.dao;

import be.leerstad.eindwerk.School;

import java.util.List;


public interface SchoolDAO {
    // CRUD methods
    public School getByPrimaryKey(String ipaddress) throws DAOException;

    public List selectAll() throws DAOException;

    public List select(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public long selectCount() throws DAOException;

    public long selectCount(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public int update(School obj) throws DAOException;

    public int insert(School obj) throws DAOException;

    public int delete(School obj) throws DAOException;

    // Finders
    public List getBySite(String site) throws DAOException;

    public List getByStreet(String street) throws DAOException;

    public List getByZip(String zip) throws DAOException;

    public List getByCity(String city) throws DAOException;
}
