// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.dao;

import be.leerstad.eindwerk.Session;

import java.util.Date;
import java.util.List;


public interface SessionDAO {
    // CRUD methods
    public Session getByPrimaryKey(String sessionid) throws DAOException;

    public List selectAll() throws DAOException;

    public List select(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public long selectCount() throws DAOException;

    public long selectCount(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public int update(Session obj) throws DAOException;

    public int insert(Session obj) throws DAOException;

    public int delete(Session obj) throws DAOException;

    // Finders
    public List getByLogfile(String logfile) throws DAOException;

    public List getByIpaddress(String ipaddress) throws DAOException;

    public List getBySessiontime(Date sessiontime) throws DAOException;

    public List getByTotaltime(Integer totaltime) throws DAOException;

    public List getByTransferredbytes(Integer transferredbytes)
        throws DAOException;

    public List getByNumberofrequests(Integer numberofrequests)
        throws DAOException;

    public List getByUserid(String userid) throws DAOException;

    public List getBySiteid(Integer siteid) throws DAOException;
}
