// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.dao;

import be.leerstad.eindwerk.Site;

import java.util.List;


public interface SiteDAO {
    // CRUD methods
    public Site getByPrimaryKey(int siteid) throws DAOException;

    public List selectAll() throws DAOException;

    public List select(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public long selectCount() throws DAOException;

    public long selectCount(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public int update(Site obj) throws DAOException;

    public int insert(Site obj) throws DAOException;

    public int delete(Site obj) throws DAOException;

    // Finders
    public List getBySite(String site) throws DAOException;
}
