// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.dao;

import be.leerstad.eindwerk.User;

import java.util.List;


public interface UserDAO {
    // CRUD methods
    public User getByPrimaryKey(String userid) throws DAOException;

    public List selectAll() throws DAOException;

    public List select(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public long selectCount() throws DAOException;

    public long selectCount(String whereStatement, Object[] bindVariables)
        throws DAOException;

    public int update(User obj) throws DAOException;

    public int insert(User obj) throws DAOException;

    public int delete(User obj) throws DAOException;

    // Finders
    public List getByName(String name) throws DAOException;

    public List getByFirstname(String firstname) throws DAOException;

    public List getByCat(String cat) throws DAOException;
}
