// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk;

import java.util.Date;


public class Logfile {
    private String logfile;
    private Date logfiledate;

    //
    // getters / setters
    //
    public String getLogfile() {
        return this.logfile;
    }

    public void setLogfile(String logfile) {
        this.logfile = logfile;
    }

    public Date getLogfiledate() {
        return this.logfiledate;
    }

    public void setLogfiledate(Date logfiledate) {
        this.logfiledate = logfiledate;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (null == obj) {
            return false;
        }

        if (obj instanceof Logfile == false) {
            return false;
        }

        Logfile other = (Logfile) obj;

        if (false == logfile.equals(other.logfile)) {
            return false;
        }

        if (false == logfiledate.equals(other.logfiledate)) {
            return false;
        }

        return true;
    }

    public int hashCode() {
        int result = 29;

        result = (29 * result) + logfile.hashCode();
        result = (29 * result) + logfiledate.hashCode();

        return result;
    }

    public String toString() {
        StringBuffer buffer = new StringBuffer("be.leerstad.eindwerk").append(".").append("Logfile")
                                                                      .append("(");

        buffer.append("[").append("logfile").append("=").append(logfile).append("]");
        buffer.append("[").append("logfiledate").append("=").append(logfiledate).append("]");

        return buffer.append(")").toString();
    }
}
