// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk;

public class Site {
    private int siteid;
    private String site;

    //
    // getters / setters
    //
    public int getSiteid() {
        return this.siteid;
    }

    public void setSiteid(int siteid) {
        this.siteid = siteid;
    }

    public String getSite() {
        return this.site;
    }

    public void setSite(String site) {
        this.site = site;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (null == obj) {
            return false;
        }

        if (obj instanceof Site == false) {
            return false;
        }

        Site other = (Site) obj;

        if (siteid != other.siteid) {
            return false;
        }

        if (false == site.equals(other.site)) {
            return false;
        }

        return true;
    }

    public int hashCode() {
        int result = 29;

        result = (29 * result) + siteid;
        result = (29 * result) + site.hashCode();

        return result;
    }

    public String toString() {
        StringBuffer buffer = new StringBuffer("be.leerstad.eindwerk").append(".").append("Site")
                                                                      .append("(");

        buffer.append("[").append("siteid").append("=").append(siteid).append("]");
        buffer.append("[").append("site").append("=").append(site).append("]");

        return buffer.append(")").toString();
    }
}
