// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk;

public class User {
    private String userid;
    private String name;
    private String firstname;
    private String cat;

    //
    // getters / setters
    //
    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getCat() {
        return this.cat;
    }

    public void setCat(String cat) {
        this.cat = cat;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (null == obj) {
            return false;
        }

        if (obj instanceof User == false) {
            return false;
        }

        User other = (User) obj;

        if (false == userid.equals(other.userid)) {
            return false;
        }

        if (false == name.equals(other.name)) {
            return false;
        }

        if (false == firstname.equals(other.firstname)) {
            return false;
        }

        if (false == cat.equals(other.cat)) {
            return false;
        }

        return true;
    }

    public int hashCode() {
        int result = 29;

        result = (29 * result) + userid.hashCode();
        result = (29 * result) + name.hashCode();
        result = (29 * result) + firstname.hashCode();
        result = (29 * result) + cat.hashCode();

        return result;
    }

    public String toString() {
        StringBuffer buffer = new StringBuffer("be.leerstad.eindwerk").append(".").append("User")
                                                                      .append("(");

        buffer.append("[").append("userid").append("=").append(userid).append("]");
        buffer.append("[").append("name").append("=").append(name).append("]");
        buffer.append("[").append("firstname").append("=").append(firstname).append("]");
        buffer.append("[").append("cat").append("=").append(cat).append("]");

        return buffer.append(")").toString();
    }
}
