// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk;

import java.util.Date;


public class Visit {
    private String visitid;
    private String logfile;
    private String ipaddress;
    private Date visittime;
    private Integer totaltime;
    private Integer transferredbytes;
    private Integer numberofrequests;
    private String user;
    private Integer siteapplicationid;
    private String ipschool;

    //
    // getters / setters
    //
    public String getVisitid() {
        return this.visitid;
    }

    public void setVisitid(String visitid) {
        this.visitid = visitid;
    }

    public String getLogfile() {
        return this.logfile;
    }

    public void setLogfile(String logfile) {
        this.logfile = logfile;
    }

    public String getIpaddress() {
        return this.ipaddress;
    }

    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    public Date getVisittime() {
        return this.visittime;
    }

    public void setVisittime(Date visittime) {
        this.visittime = visittime;
    }

    public Integer getTotaltime() {
        return this.totaltime;
    }

    public void setTotaltime(Integer totaltime) {
        this.totaltime = totaltime;
    }

    public Integer getTransferredbytes() {
        return this.transferredbytes;
    }

    public void setTransferredbytes(Integer transferredbytes) {
        this.transferredbytes = transferredbytes;
    }

    public Integer getNumberofrequests() {
        return this.numberofrequests;
    }

    public void setNumberofrequests(Integer numberofrequests) {
        this.numberofrequests = numberofrequests;
    }

    public String getUser() {
        return this.user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public Integer getSiteapplicationid() {
        return this.siteapplicationid;
    }

    public void setSiteapplicationid(Integer siteapplicationid) {
        this.siteapplicationid = siteapplicationid;
    }

    public String getIpschool() {
        return this.ipschool;
    }

    public void setIpschool(String ipschool) {
        this.ipschool = ipschool;
    }

    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (null == obj) {
            return false;
        }

        if (obj instanceof Visit == false) {
            return false;
        }

        Visit other = (Visit) obj;

        if (false == visitid.equals(other.visitid)) {
            return false;
        }

        if (false == logfile.equals(other.logfile)) {
            return false;
        }

        if (false == ipaddress.equals(other.ipaddress)) {
            return false;
        }

        if (false == visittime.equals(other.visittime)) {
            return false;
        }

        if (false == totaltime.equals(other.totaltime)) {
            return false;
        }

        if (false == transferredbytes.equals(other.transferredbytes)) {
            return false;
        }

        if (false == numberofrequests.equals(other.numberofrequests)) {
            return false;
        }

        if (false == user.equals(other.user)) {
            return false;
        }

        if (false == siteapplicationid.equals(other.siteapplicationid)) {
            return false;
        }

        if (false == ipschool.equals(other.ipschool)) {
            return false;
        }

        return true;
    }

    public int hashCode() {
        int result = 29;

        result = (29 * result) + visitid.hashCode();
        result = (29 * result) + logfile.hashCode();
        result = (29 * result) + ipaddress.hashCode();
        result = (29 * result) + visittime.hashCode();
        result = (29 * result) + totaltime.hashCode();
        result = (29 * result) + transferredbytes.hashCode();
        result = (29 * result) + numberofrequests.hashCode();
        result = (29 * result) + user.hashCode();
        result = (29 * result) + siteapplicationid.hashCode();
        result = (29 * result) + ipschool.hashCode();

        return result;
    }

    public String toString() {
        StringBuffer buffer = new StringBuffer("be.leerstad.eindwerk").append(".").append("Visit")
                                                                      .append("(");

        buffer.append("[").append("visitid").append("=").append(visitid).append("]");
        buffer.append("[").append("logfile").append("=").append(logfile).append("]");
        buffer.append("[").append("ipaddress").append("=").append(ipaddress).append("]");
        buffer.append("[").append("visittime").append("=").append(visittime).append("]");
        buffer.append("[").append("totaltime").append("=").append(totaltime).append("]");
        buffer.append("[").append("transferredbytes").append("=").append(transferredbytes)
              .append("]");
        buffer.append("[").append("numberofrequests").append("=").append(numberofrequests)
              .append("]");
        buffer.append("[").append("user").append("=").append(user).append("]");
        buffer.append("[").append("siteapplicationid").append("=").append(siteapplicationid)
              .append("]");
        buffer.append("[").append("ipschool").append("=").append(ipschool).append("]");

        return buffer.append(")").toString();
    }
}
