// Generated by DB Solo 5.2.1 on Feb 14, 2017 at 9:31:39 PM
package be.leerstad.eindwerk.test;

import be.leerstad.eindwerk.Site;
import be.leerstad.eindwerk.jdbc.SiteDAOImpl;

import junit.framework.TestCase;

import java.sql.Connection;


public class SiteDAOImplTest extends TestCase {
    private Connection conn = null;

    protected void setUp() throws Exception {
        conn = TestUtil.getConnection();
    }

    protected void tearDown() throws Exception {
        TestUtil.closeConnection(conn);
        conn = null;
    }

    public void testSelect() {
        SiteDAOImpl obj = new SiteDAOImpl(getConn());

        try {
            obj.selectAll();
        }
        catch (Exception e) {
            e.printStackTrace();
            assertTrue(false);
        }
    }

    public void testDelete() {
        try {
            SiteDAOImpl dao = new SiteDAOImpl(getConn());

            Site obj = insert(getConn());
            int before = dao.selectAll().size();
            int after;

            dao.delete(obj);
            after = dao.selectAll().size();
            assertTrue(after == (before - 1));
            getConn().commit();
        }
        catch (Exception e) {
            e.printStackTrace();
            assertFalse(true);
        }
    }

    public void testFinders() {
        try {
            SiteDAOImpl dao = new SiteDAOImpl(getConn());
            Site obj = insert(getConn());

            assertTrue(dao.getBySite(obj.getSite()).size() > 0);
            dao.delete(obj);

            getConn().commit();
        }
        catch (Exception e) {
            e.printStackTrace();
            assertFalse(true);
        }
    }

    public void testInsert() {
        try {
            SiteDAOImpl dao = new SiteDAOImpl(getConn());

            int before = dao.selectAll().size();
            Site obj = insert(getConn());
            int after = dao.selectAll().size();

            assertNotNull(obj);
            assertTrue(after == (before + 1));
            getConn().commit();
        }
        catch (Exception e) {
            e.printStackTrace();
            assertFalse(true);
        }
    }

    public void testUpdate() {
        try {
            // insert
            SiteDAOImpl dao = new SiteDAOImpl(getConn());
            Site obj = insert(getConn());

            // update
            String tempsite = TestUtil.random_String();

            obj.setSite(tempsite);
            dao.update(obj);

            // verify results
            obj = dao.getByPrimaryKey(obj.getSiteid());

            assertEquals(tempsite, obj.getSite());
            getConn().commit();
        }
        catch (Exception e) {
            e.printStackTrace();
            assertFalse(true);
        }
    }

    protected static Site insert(Connection conn) throws Exception {
        Site obj = new Site();
        SiteDAOImpl dao = new SiteDAOImpl(conn);

        obj.setSiteid(TestUtil.random_int());
        obj.setSite(TestUtil.random_String());

        dao.insert(obj);

        return obj;
    }

    private Connection getConn() {
        return conn;
    }
}
